### ISSUE TITLE
Ubuntu gcc 版本

### ISSUE THREAD

**Issue by FanYiHG** [yehengchen/Ubuntu-16.04-Deep-Learning-Environment-Setup#1]
Ubuntu16.04的GCC版本需要降到4.8吗，默认是5.4

**Comment by yehengchen** [comment]
@FanYiHG 我这里使用的gcc版本都是默认的

`Ubuntu 16.04: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) `
`Ubuntu 18.04: gcc (Ubuntu 6.5.0-2ubuntu1~18.04)`
