### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by FanYiHG** [yehengchen/Ubuntu-16.04-Deep-Learning-Environment-Setup#2]
前面的英伟达驱动，cuda和cudnn都成功安装了。但Tensorflow虽然显示成功安装了，但是import 它时会发生“Segmentation fault (core dumped)”，请问这个问题如何解决？十分感谢！

**Comment by yehengchen** [comment]
@FanYiHG 可以试一下在 `import tensorflow`之前加上
```
import numpy
import matplotlib
```

**Comment by FanYiHG** [comment]
是cudnn装的时候输错命令了，卸载重装后可以了，谢谢你～
